export const autocompleteOptions = [
  { name: 'Azim Saiyed', subText: 'azim+5@writer.com', id: 3705 },
  { name: 'Doris Jwo', subText: 'doris+feb20.1@qordoba.com', id: 3166 },
  { name: 'Ethan Harry', subText: 'ethan@qordoba.com', id: 1078 },
  { name: 'Franzi Wittleder', subText: 'franzi@qordoba.com', id: 1077 },
  { name: 'Azim Saiyed', subText: 'gaxewab329@kamismail.com', id: 1778 },
  { name: 'Genalyn Capio', subText: 'genalyn@qordoba.com', id: 1036 },
  { name: 'Grzegorz Walen', subText: 'grzegorz@xxxqordoba.com', id: 1117 },
  { name: 'Helen Helen', subText: 'helen.ulasevich@yellow.systems', id: 2045 },
  { name: 'Hussam1 Otri', subText: 'hussam+1@qordoba.com', id: 1023 },
  { name: '', subText: 'hussam+1h@qordoba.com', id: 1788 },
  { name: 'asdasd asdas', subText: 'asdasdasd@asdas.dasd', id: 3855 },
  { name: '', subText: 'asdfa@sadf.sghs', id: 4068 },
  { name: '', subText: 'asdfasfd@sadfasfd.fs', id: 4067 },
];

export const defaultValue = [
  { name: 'Azim Saiyed', subText: 'gaxewab329@kamismail.com', id: 1778 },
  { name: 'Genalyn Capio', subText: 'genalyn@qordoba.com', id: 1036 },
  { name: 'Grzegorz Walen', subText: 'grzegorz@xxxqordoba.com', id: 1117 },
];

export const selectOptions = [
  { id: '2418', name: 'Use my own', active: false },
  { id: '2558', name: 'styleguideCreate', color: 'var(--avatar-7)', active: false },
  { id: '2476', name: 'New Team 203942039', color: 'var(--avatar-5)', active: false },
  { id: '2522', name: 'Doris 9', color: 'var(--avatar-3)', active: false },
  { id: '2527', name: 'Doris 14', color: 'var(--avatar-8)', active: false },
  { id: '2414', name: 'Customer Support & Success', color: 'var(--avatar-7)', active: false },
  { id: '2528', name: 'Doris 15', color: 'var(--avatar-1)', active: false },
  { id: '2519', name: 'Doris 6', color: 'var(--avatar-8)', active: false },
  { id: '2526', name: 'Doris 13', color: 'var(--avatar-7)', active: false },
  { id: '2548', name: 'superlongteamnamethatdoesntend', color: 'var(--avatar-5)', active: false },
  { id: '2421', name: 'Content Marketing Blogs', color: 'var(--avatar-6)', active: false },
  { id: '2724', name: 'DJ 3/2', color: 'var(--avatar-5)', active: false },
  { id: '2518', name: 'Doris 5', color: 'var(--avatar-7)', active: false },
  { id: '2521', name: 'Doris 8', color: 'var(--avatar-2)', active: false },
  { id: '2520', name: 'Doris 7', color: 'var(--avatar-1)', active: false },
  { id: '2420', name: 'Technical Support', color: 'var(--avatar-5)', active: false },
  { id: '2532', name: 'Doris 19', color: 'var(--avatar-5)', active: false },
  { id: '2749', name: 'Styleguide Team', color: 'var(--avatar-6)', active: false },
  { id: '2232', name: 'Asdasd', color: 'var(--avatar-1)', active: false },
  { id: '2792', name: 'azzzz2', color: 'var(--avatar-1)', active: false },
  { id: '2674', name: 'PK test', color: 'var(--avatar-3)', active: false },
  { id: '2908', name: 'm team', color: 'var(--avatar-5)', active: false },
  { id: '2864', name: 'Yakiv', color: 'var(--avatar-1)', active: false },
  { id: '2515', name: 'Doris ', color: 'var(--avatar-4)', active: false },
  { id: '2514', name: 'Doris ', color: 'var(--avatar-3)', active: false },
  { id: '2474', name: 'test 1', color: 'var(--avatar-3)', active: false },
  { id: '2524', name: 'Doris 11', color: 'var(--avatar-5)', active: false },
  { id: '2523', name: 'Doris 10', color: 'var(--avatar-4)', active: false },
  { id: '2450', name: 'Test', color: 'var(--avatar-3)', active: false },
];
